export const possibleSkills = [
  "JavaScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "PHP",
  "Swift",
  "Kotlin",
  "Ruby",
  "TypeScript",
  "Go",
  "Rust",
  "Shell scripting",
  "R",
  "Scala",
  "Perl",
  "Lua",
  "Haskell",
  "Matlab",
  "Julia",
  "Objective-C",
  "Groovy",
  "CoffeeScript",
  "Visual Basic .NET",
  "Delphi",
  "Dart",
  "F#",
  "Pascal",
  "Assembly",
  "Fortran",
  "Cobol",
  "Ada",
  "HTML",
  "CSS",
  "Sass",
  "Less",
  "Bootstrap",
  "Tailwind CSS",
  "Material-UI",
  "Bulma",
  "Semantic UI",
  "Foundation",
  "UIKit",
  "Ant Design",
  "React",
  "Vue.js",
  "Angular",
  "Svelte",
  "Ember.js",
  "Meteor.js",
  "Backbone.js",
  "Aurelia",
  "Mithril",
  "Polymer",
  "Preact",
  "Inferno",
  "Stencil",
  "Lit",
  "Solid",
  "Dojo",
  "jQuery",
  "Node.js",
  "Deno",
  "Express",
  "Koa",
  "Hapi",
  "Fastify",
  "NestJS",
  "Feathers",
  "Sails.js",
  "LoopBack",
  "Total.js",
  "Restify",
  "ActionHero",
  "Socket.IO",
  "Django",
  "Flask",
  "Pyramid",
  "Web2py",
  "TurboGears",
  "Tornado",
  "Sanic",
  "FastAPI",
  "Bottle",
  "Falcon",
  "Hug",
  "Morepath",
  "CherryPy",
  "AIOHTTP",
  "Ray",
  "Dash",
  "Anvil",
  "Masonite",
  "Laravel",
  "Symfony",
  "CodeIgniter",
  "Yii",
  "Zend Framework",
  "CakePHP",
  "Phalcon",
  "Slim",
  "FuelPHP",
  "PHPixie",
  "Nette",
  "Laminas Project",
  "JHipster",
  "Spring",
  "Play Framework",
  "Struts",
  "Hibernate",
  "Apache Wicket",
  "Grails",
  "Vaadin",
  "Blade",
  "Quarkus",
  "Micronaut",
  "Ruby on Rails",
  "Sinatra",
  "Hanami",
  "Trailblazer",
  "Padrino",
  "NYNY",
  "Cuba",
  "ASP.NET",
  "ASP.NET MVC",
  "ASP.NET Web API",
  "ASP.NET Core",
  "Blazor",
  "WCF",
  "Xamarin",
  "Uno Platform",
  "Avalonia",
  "MAUI",
  "Unity",
  "Unreal Engine",
  "Godot",
  "GameMaker Studio",
  "Cocos2d",
  "Amazon Web Services",
  "Google Cloud Platform",
  "Microsoft Azure",
  "IBM Cloud",
  "Oracle Cloud",
  "Alibaba Cloud",
  "Salesforce",
  "Docker",
  "Kubernetes",
  "OpenShift",
  "Rancher",
  "Nomad",
  "Mesos",
  "Swarm",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "SaltStack",
  "Elastic Stack",
  "Prometheus",
  "Grafana",
  "Graylog",
  "Splunk",
  "Nagios",
  "Zabbix",
  "DataDog",
  "Selenium",
  "Cypress",
  "Puppeteer",
  "Playwright",
  "WebDriverIO",
  "Protractor",
  "Nightwatch.js",
  "TestCafe",
  "Jest",
  "Mocha",
  "Chai",
  "Jasmine",
  "Enzyme",
  "Ava",
  "Tape",
  "QUnit",
  "Sinon.JS",
  "Karma",
  "Istanbul",
  "Cucumber.js",
  "RSpec",
  "MiniTest",
  "Capybara",
  "FactoryBot",
  "JUnit",
  "TestNG",
  "Mockito",
  "Arquillian",
  "PowerMock",
  "EasyMock",
  "JMock",
  "Hamcrest",
  "NUnit",
  "xUnit.net",
  "SpecFlow",
  "NSubstitute",
  "FakeItEasy",
  "Moq",
  "Atata",
  "WireMock.Net",
  "PHPUnit",
  "Codeception",
  "Behat",
  "PHPSpec",
  "Peridot",
  "Kahlan",
  "Atoum",
  "Storybook",
  "Figma",
  "Sketch",
  "InVision Studio",
  "Adobe XD",
  "Framer",
  "Axure RP",
  "Affinity Designer",
  "UXPin",
  "Balsamiq",
  "QuarkXPress",
  "CorelDRAW",
  "GIMP",
  "Inkscape",
  "Paint.NET",
  "Pixlr",
  "Canva",
  "Gravit Designer",
  "Vectornator",
  "Krita",
  "Photopea",
  "Xara Designer Pro X",
  "Serif Affinity Photo",
  "Capture One",
  "ACDSee Photo Studio",
  "DxO PhotoLab",
  "Luminar",
  "ON1 Photo RAW",
  "Exposure X",
  "Darktable",
  "RawTherapee",
  "LightZone",
  "PhotoDirector",
  "Adobe Lightroom",
  "After Effects",
  "Premiere Pro",
  "Final Cut Pro X",
  "DaVinci Resolve",
  "iMovie",
  "Camtasia",
  "Filmora",
  "Shotcut",
  "HitFilm Express",
  "Lightworks",
  "Pinnacle Studio",
  "Corel VideoStudio",
  "CyberLink PowerDirector",
  "Blender",
  "SketchUp",
  "AutoCAD",
  "Tinkercad",
  "Fusion 360",
  "3ds Max",
  "Maya",
  "Cinema 4D",
  "ZBrush",
  "Rhinoceros",
  "Revit",
  "Inventor",
  "SolidWorks",
  "CATIA",
  "PTC Creo",
  "Siemens NX",
  "MicroStation",
  "ANSYS",
  "Solid Edge",
  "FreeCAD",
  "OpenSCAD",
  "Sculptris",
  "Tinkerine Suite",
  "Ultimaker Cura",
  "MatterControl",
  "PrusaSlicer",
  "Repetier-Host",
  "Photon Workshop",
  "FlashPrint",
  "Lychee Slicer",
  "OctoPrint",
  "WordPress",
  "Joomla",
  "Drupal",
  "Magento",
  "Shopify",
  "PrestaShop",
  "OpenCart",
  "WooCommerce",
  "BigCommerce",
  "osCommerce",
  "Squarespace",
  "Wix",
  "Weebly",
  "HubSpot",
  "Salesforce Commerce Cloud",
  "Volusion",
  "Zoho Commerce",
  "Odoo",
  "3dcart",
  "Mozello",
  "Easy Digital Downloads",
  "Ecwid",
  "X-Cart",
  "CoreCommerce",
  "CS-Cart",
  "NetSuite SuiteCommerce",
  "Big Cartel",
  "Sellfy",
  "Pimcore",
  "Aimeos",
  "Jumpseller",
  "FastSpring",
  "E-junkie",
  "SendOwl",
  "Gumroad",
  "PayPro Global",
  "Paddle",
  "Simple Goods",
  "FoxyCart",
  "Kajabi",
  "Znode",
  "nopCommerce",
  "Vue Storefront",
  "Sylius",
  "AvoRed",
  "OroCommerce",
  "Virto Commerce",
  "Elastic Path",
  "Spryker",
  "Miva Merchant",
  "Reaction Commerce",
  "Saleor",
  "PrestaShop Ready",
  "Zen Cart",
  "Spree Commerce",
  "Snipcart",
  "Lightspeed eCom",
  "Kartra",
  "Commercetools",
  "Episerver",
  "Shopware",
  "Hybris",
  "2Checkout",
  "Avangate",
  "SamCart",
  "Checkout X",
  "VTEX",
  "CloudCart",
  "Algolia",
  "Elasticsearch",
  "Solr",
  "Apache Lucene",
  "Amazon CloudSearch",
  "Microsoft Azure Search",
  "Google Cloud Search",
  "Swiftype",
  "AddSearch",
  "SearchSpring",
  "Soovle",
  "SLI Systems",
  "Cludo",
  "SearchBlox",
  "Search.io",
  "Sajari",
  "SearchTap",
  "SearchNode",
  "Searchify",
  "InstantSearch+",
  "Nextopia",
  "Yext Answers",
  "Site Search 360",
  "Expertrec",
  "Inbenta",
  "Findologic",
  "Luigi’s Box",
  "Constructor.io",
  "Klevu",
  "Unbxd",
  "Coveo",
  "FACT-Finder",
  "Twigkit",
  "Dieselpoint",
  "Datafari",
  "Mindbreeze",
  "IBM Watson Discovery",
  "Cognitive Search",
  "TeraText",
  "SciGraph",
  "Ontotext",
  "Concept Searching",
  "Funnelback",
  "AlphaSense",
  "iManage RAVN",
  "Dassault Exalead",
  "BA Insight",
  "Attivio",
  "Raytion",
  "Xendo",
  "Loop54",
  "Doofinder",
  "Wiser Search",
  "Elastic Suite",
  "SmarterHQ",
  "Apptus",
  "Attraqt",
  "Prisync",
  "Competera",
  "SpotLite",
  "Price2Spy",
  "RepricerExpress",
  "SellerActive",
  "Incompetitor",
  "PriceLab",
  "Omnia Dynamic Pricing",
  "Quick Sales",
  "Skuuudle",
  "Prisync",
  "Competera",
  "SpotLite",
  "Price2Spy",
  "RepricerExpress",
  "SellerActive",
  "Incompetitor",
  "PriceLab",
  "Omnia Dynamic Pricing",
  "Quick Sales",
  "Skuuudle",
  "RepriceIt",
  "Feedvisor",
  "Repricer.com",
  "Aura",
  "StreetPricer",
  "Informed.co",
  "Ecomdash",
  "Priceyak",
  "Reepricer",
  "Snipe Retail",
  "Seller Republic",
  "Xsellco Price Manager",
  "PrimaSeller",
  "GoAura",
  "Appeagle",
  "Reprice Solution",
  "Eagle Eye",
  "Revionics",
  "Blue Yonder",
  "Dynamic Yield",
  "Boomerang Commerce",
  "BlackCurve",
  "QuickLizard",
  "Omnia Pricewatch",
  "PriceEdge",
  "PROS",
  "Perfect Price",
  "Pricefx",
  "Diginius",
  "Intuendi",
  "NetRivals",
  "PriceBeam",
  "Vendavo",
  "Zilliant",
  "SyncForce",
  "JDA Software",
  "Engage3",
  "IQVIA",
  "Verenia",
  "360pi",
  "RevCascade",
  "Upstream Commerce",
  "WooCommerce Product Feed",
  "SAS",
  "Clear Demand",
  "First Insight",
  "Logility",
  "Oracle Retail",
  "Infor Retail",
  "Manthan Software",
  "Antuit",
  "Flintfox RMx",
  "PricingHUB",
  "Pricemoov",
  "Kompyte",
  "PriceTrack",
  "SkuBrain",
  "Seller Dynamics",
  "Pricesearch",
  "Board",
  "3Qube",
  "Cin7",
  "Vistaar",
  "Acumatica",
  "Toolio",
  "Wigzo",
  "Jetti",
  "TrackStreet",
  "PriceSpider",
  "Sku Grid",
  "Repricing Co",
  "Algopix",
  "Pricestack",
  "Sposea",
  "Toolbox",
  "Seller Snap",
  "IntelliTrack",
  "Kommerce",
  "SellerMobile",
  "Pricemoov",
  "ReactorNet",
  "MerchLogix Planogramming",
  "Smart Merchandiser",
  "aWorkbook",
  "Smart Assortment",
  "NetSuite SuiteCommerce",
  "Salesforce Commerce Cloud",
  "JDA Assortment",
  "Cumulus Retail",
  "JustEnough Assortment Planning",
  "TXT Retail",
  "iVend Retail",
  "MerchLogix Assortment Planning",
  "IBM Watson Order Optimizer",
  "Oracle Retail Assortment Planning",
  "JDA Floor Planning",
  "Smart Merchandiser",
  "JustEnough Merchandise Financial Planning",
  "Oracle Retail Merchandise Financial Planning",
  "TXTMap",
  "Mi9 Retail",
  "IBM Watson Order Optimizer",
  "Blue Yonder",
  "Relex Solutions",
  "7thonline",
  "Ginesys",
  "TXT Retail",
  "Oracle Retail Customer Engagement",
  "Island Pacific SmartSuite",
  "4R Systems",
  "Cin7",
  "Revionics",
  "Celect",
  "Antuit",
  "JustEnough Merchandise & Assortment Management",
  "SAS Size Profiling",
  "Logility",
  "Infor Retail Demand Management",
  "Mi9 Retail",
  "4R Systems",
  "SAS Markdown Optimization",
  "JustEnough Markdown Planning",
  "Oracle Retail Regular Price Optimization",
  "SAS Regular Price Optimization",
  "SAS Size Optimization",
  "Oracle Retail Size Profile Optimization",
  "JustEnough Store Clustering",
  "SAS Store Clustering",
  "SAS Space Optimization",
  "Oracle Retail Space Optimization",
  "JustEnough Space Planning",
  "Blue Yonder",
  "Oracle Retail Assortment & Item Planning",
  "JustEnough Assortment & Item Planning",
  "Oracle Retail Advanced Clustering",
  "SAS Promotion Optimization",
  "JustEnough Promotion Management",
  "Oracle Retail Promotion Planning & Optimization"
];